require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Shop::OrdersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Shop::Order. As you add validations to Shop::Order, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Shop::OrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shop_orders as @shop_orders" do
      order = Shop::Order.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:shop_orders)).to eq([order])
    end
  end

  describe "GET show" do
    it "assigns the requested shop_order as @shop_order" do
      order = Shop::Order.create! valid_attributes
      get :show, {:id => order.to_param}, valid_session
      expect(assigns(:shop_order)).to eq(order)
    end
  end

  describe "GET new" do
    it "assigns a new shop_order as @shop_order" do
      get :new, {}, valid_session
      expect(assigns(:shop_order)).to be_a_new(Shop::Order)
    end
  end

  describe "GET edit" do
    it "assigns the requested shop_order as @shop_order" do
      order = Shop::Order.create! valid_attributes
      get :edit, {:id => order.to_param}, valid_session
      expect(assigns(:shop_order)).to eq(order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shop::Order" do
        expect {
          post :create, {:shop_order => valid_attributes}, valid_session
        }.to change(Shop::Order, :count).by(1)
      end

      it "assigns a newly created shop_order as @shop_order" do
        post :create, {:shop_order => valid_attributes}, valid_session
        expect(assigns(:shop_order)).to be_a(Shop::Order)
        expect(assigns(:shop_order)).to be_persisted
      end

      it "redirects to the created shop_order" do
        post :create, {:shop_order => valid_attributes}, valid_session
        expect(response).to redirect_to(Shop::Order.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shop_order as @shop_order" do
        post :create, {:shop_order => invalid_attributes}, valid_session
        expect(assigns(:shop_order)).to be_a_new(Shop::Order)
      end

      it "re-renders the 'new' template" do
        post :create, {:shop_order => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shop_order" do
        order = Shop::Order.create! valid_attributes
        put :update, {:id => order.to_param, :shop_order => new_attributes}, valid_session
        order.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested shop_order as @shop_order" do
        order = Shop::Order.create! valid_attributes
        put :update, {:id => order.to_param, :shop_order => valid_attributes}, valid_session
        expect(assigns(:shop_order)).to eq(order)
      end

      it "redirects to the shop_order" do
        order = Shop::Order.create! valid_attributes
        put :update, {:id => order.to_param, :shop_order => valid_attributes}, valid_session
        expect(response).to redirect_to(order)
      end
    end

    describe "with invalid params" do
      it "assigns the shop_order as @shop_order" do
        order = Shop::Order.create! valid_attributes
        put :update, {:id => order.to_param, :shop_order => invalid_attributes}, valid_session
        expect(assigns(:shop_order)).to eq(order)
      end

      it "re-renders the 'edit' template" do
        order = Shop::Order.create! valid_attributes
        put :update, {:id => order.to_param, :shop_order => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shop_order" do
      order = Shop::Order.create! valid_attributes
      expect {
        delete :destroy, {:id => order.to_param}, valid_session
      }.to change(Shop::Order, :count).by(-1)
    end

    it "redirects to the shop_orders list" do
      order = Shop::Order.create! valid_attributes
      delete :destroy, {:id => order.to_param}, valid_session
      expect(response).to redirect_to(shop_orders_url)
    end
  end

end
