class CreateArtworks < ActiveRecord::Migration
  def change
    drop_table :artworks
    create_table :artworks do |t|
      t.string   "title"
      t.text     "body"
      t.string   "file"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.string   "thumb"
      t.string   "image_id"
      t.string   "basename"
      t.string   "ext"
      t.string   "image_size"
      t.string   "mime"
      t.string   "image_type"
      t.string   "md5hash"
      t.string   "width"
      t.string   "height"
      t.string   "date_recorded"
      t.string   "date_file_created"
      t.string   "date_file_modified"
      t.string   "description"
      t.string   "location"
      t.string   "aspect_ratio"
      t.string   "city"
      t.string   "state"
      t.string   "country"
      t.string   "country_code"
      t.text     "keywords"
      t.string   "aperture"
      t.string   "exposure_compensation"
      t.string   "exposure_mode"
      t.string   "exposure_time"
      t.string   "flash"
      t.string   "focal_length"
      t.string   "f_number"
      t.string   "iso"
      t.string   "light_value"
      t.string   "metering_mode"
      t.string   "shutter_speed"
      t.string   "white_balance"
      t.string   "device_name"
      t.string   "device_vendor"
      t.string   "device_software"
      t.string   "latitude"
      t.string   "longitude"
      t.string   "orientation"
      t.string   "has_clipping_path"
      t.string   "creator"
      t.string   "author"
      t.string   "copyright"
      t.string   "frame_count"
      t.text     "copyright_notice"
      t.belongs_to :account, index: true
    end

  end
end
