require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CmsProfilesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CmsProfile. As you add validations to CmsProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CmsProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cms_profiles as @cms_profiles" do
      cms_profile = CmsProfile.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cms_profiles)).to eq([cms_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested cms_profile as @cms_profile" do
      cms_profile = CmsProfile.create! valid_attributes
      get :show, {:id => cms_profile.to_param}, valid_session
      expect(assigns(:cms_profile)).to eq(cms_profile)
    end
  end

  describe "GET new" do
    it "assigns a new cms_profile as @cms_profile" do
      get :new, {}, valid_session
      expect(assigns(:cms_profile)).to be_a_new(CmsProfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested cms_profile as @cms_profile" do
      cms_profile = CmsProfile.create! valid_attributes
      get :edit, {:id => cms_profile.to_param}, valid_session
      expect(assigns(:cms_profile)).to eq(cms_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CmsProfile" do
        expect {
          post :create, {:cms_profile => valid_attributes}, valid_session
        }.to change(CmsProfile, :count).by(1)
      end

      it "assigns a newly created cms_profile as @cms_profile" do
        post :create, {:cms_profile => valid_attributes}, valid_session
        expect(assigns(:cms_profile)).to be_a(CmsProfile)
        expect(assigns(:cms_profile)).to be_persisted
      end

      it "redirects to the created cms_profile" do
        post :create, {:cms_profile => valid_attributes}, valid_session
        expect(response).to redirect_to(CmsProfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cms_profile as @cms_profile" do
        post :create, {:cms_profile => invalid_attributes}, valid_session
        expect(assigns(:cms_profile)).to be_a_new(CmsProfile)
      end

      it "re-renders the 'new' template" do
        post :create, {:cms_profile => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cms_profile" do
        cms_profile = CmsProfile.create! valid_attributes
        put :update, {:id => cms_profile.to_param, :cms_profile => new_attributes}, valid_session
        cms_profile.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cms_profile as @cms_profile" do
        cms_profile = CmsProfile.create! valid_attributes
        put :update, {:id => cms_profile.to_param, :cms_profile => valid_attributes}, valid_session
        expect(assigns(:cms_profile)).to eq(cms_profile)
      end

      it "redirects to the cms_profile" do
        cms_profile = CmsProfile.create! valid_attributes
        put :update, {:id => cms_profile.to_param, :cms_profile => valid_attributes}, valid_session
        expect(response).to redirect_to(cms_profile)
      end
    end

    describe "with invalid params" do
      it "assigns the cms_profile as @cms_profile" do
        cms_profile = CmsProfile.create! valid_attributes
        put :update, {:id => cms_profile.to_param, :cms_profile => invalid_attributes}, valid_session
        expect(assigns(:cms_profile)).to eq(cms_profile)
      end

      it "re-renders the 'edit' template" do
        cms_profile = CmsProfile.create! valid_attributes
        put :update, {:id => cms_profile.to_param, :cms_profile => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cms_profile" do
      cms_profile = CmsProfile.create! valid_attributes
      expect {
        delete :destroy, {:id => cms_profile.to_param}, valid_session
      }.to change(CmsProfile, :count).by(-1)
    end

    it "redirects to the cms_profiles list" do
      cms_profile = CmsProfile.create! valid_attributes
      delete :destroy, {:id => cms_profile.to_param}, valid_session
      expect(response).to redirect_to(cms_profiles_url)
    end
  end

end
