require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DefaultImagesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DefaultImage. As you add validations to DefaultImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefaultImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all default_images as @default_images" do
      default_image = DefaultImage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:default_images)).to eq([default_image])
    end
  end

  describe "GET show" do
    it "assigns the requested default_image as @default_image" do
      default_image = DefaultImage.create! valid_attributes
      get :show, {:id => default_image.to_param}, valid_session
      expect(assigns(:default_image)).to eq(default_image)
    end
  end

  describe "GET new" do
    it "assigns a new default_image as @default_image" do
      get :new, {}, valid_session
      expect(assigns(:default_image)).to be_a_new(DefaultImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested default_image as @default_image" do
      default_image = DefaultImage.create! valid_attributes
      get :edit, {:id => default_image.to_param}, valid_session
      expect(assigns(:default_image)).to eq(default_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DefaultImage" do
        expect {
          post :create, {:default_image => valid_attributes}, valid_session
        }.to change(DefaultImage, :count).by(1)
      end

      it "assigns a newly created default_image as @default_image" do
        post :create, {:default_image => valid_attributes}, valid_session
        expect(assigns(:default_image)).to be_a(DefaultImage)
        expect(assigns(:default_image)).to be_persisted
      end

      it "redirects to the created default_image" do
        post :create, {:default_image => valid_attributes}, valid_session
        expect(response).to redirect_to(DefaultImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved default_image as @default_image" do
        post :create, {:default_image => invalid_attributes}, valid_session
        expect(assigns(:default_image)).to be_a_new(DefaultImage)
      end

      it "re-renders the 'new' template" do
        post :create, {:default_image => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested default_image" do
        default_image = DefaultImage.create! valid_attributes
        put :update, {:id => default_image.to_param, :default_image => new_attributes}, valid_session
        default_image.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested default_image as @default_image" do
        default_image = DefaultImage.create! valid_attributes
        put :update, {:id => default_image.to_param, :default_image => valid_attributes}, valid_session
        expect(assigns(:default_image)).to eq(default_image)
      end

      it "redirects to the default_image" do
        default_image = DefaultImage.create! valid_attributes
        put :update, {:id => default_image.to_param, :default_image => valid_attributes}, valid_session
        expect(response).to redirect_to(default_image)
      end
    end

    describe "with invalid params" do
      it "assigns the default_image as @default_image" do
        default_image = DefaultImage.create! valid_attributes
        put :update, {:id => default_image.to_param, :default_image => invalid_attributes}, valid_session
        expect(assigns(:default_image)).to eq(default_image)
      end

      it "re-renders the 'edit' template" do
        default_image = DefaultImage.create! valid_attributes
        put :update, {:id => default_image.to_param, :default_image => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested default_image" do
      default_image = DefaultImage.create! valid_attributes
      expect {
        delete :destroy, {:id => default_image.to_param}, valid_session
      }.to change(DefaultImage, :count).by(-1)
    end

    it "redirects to the default_images list" do
      default_image = DefaultImage.create! valid_attributes
      delete :destroy, {:id => default_image.to_param}, valid_session
      expect(response).to redirect_to(default_images_url)
    end
  end

end
