require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DigirampEmailsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DigirampEmail. As you add validations to DigirampEmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DigirampEmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all digiramp_emails as @digiramp_emails" do
      digiramp_email = DigirampEmail.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:digiramp_emails)).to eq([digiramp_email])
    end
  end

  describe "GET show" do
    it "assigns the requested digiramp_email as @digiramp_email" do
      digiramp_email = DigirampEmail.create! valid_attributes
      get :show, {:id => digiramp_email.to_param}, valid_session
      expect(assigns(:digiramp_email)).to eq(digiramp_email)
    end
  end

  describe "GET new" do
    it "assigns a new digiramp_email as @digiramp_email" do
      get :new, {}, valid_session
      expect(assigns(:digiramp_email)).to be_a_new(DigirampEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested digiramp_email as @digiramp_email" do
      digiramp_email = DigirampEmail.create! valid_attributes
      get :edit, {:id => digiramp_email.to_param}, valid_session
      expect(assigns(:digiramp_email)).to eq(digiramp_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DigirampEmail" do
        expect {
          post :create, {:digiramp_email => valid_attributes}, valid_session
        }.to change(DigirampEmail, :count).by(1)
      end

      it "assigns a newly created digiramp_email as @digiramp_email" do
        post :create, {:digiramp_email => valid_attributes}, valid_session
        expect(assigns(:digiramp_email)).to be_a(DigirampEmail)
        expect(assigns(:digiramp_email)).to be_persisted
      end

      it "redirects to the created digiramp_email" do
        post :create, {:digiramp_email => valid_attributes}, valid_session
        expect(response).to redirect_to(DigirampEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved digiramp_email as @digiramp_email" do
        post :create, {:digiramp_email => invalid_attributes}, valid_session
        expect(assigns(:digiramp_email)).to be_a_new(DigirampEmail)
      end

      it "re-renders the 'new' template" do
        post :create, {:digiramp_email => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested digiramp_email" do
        digiramp_email = DigirampEmail.create! valid_attributes
        put :update, {:id => digiramp_email.to_param, :digiramp_email => new_attributes}, valid_session
        digiramp_email.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested digiramp_email as @digiramp_email" do
        digiramp_email = DigirampEmail.create! valid_attributes
        put :update, {:id => digiramp_email.to_param, :digiramp_email => valid_attributes}, valid_session
        expect(assigns(:digiramp_email)).to eq(digiramp_email)
      end

      it "redirects to the digiramp_email" do
        digiramp_email = DigirampEmail.create! valid_attributes
        put :update, {:id => digiramp_email.to_param, :digiramp_email => valid_attributes}, valid_session
        expect(response).to redirect_to(digiramp_email)
      end
    end

    describe "with invalid params" do
      it "assigns the digiramp_email as @digiramp_email" do
        digiramp_email = DigirampEmail.create! valid_attributes
        put :update, {:id => digiramp_email.to_param, :digiramp_email => invalid_attributes}, valid_session
        expect(assigns(:digiramp_email)).to eq(digiramp_email)
      end

      it "re-renders the 'edit' template" do
        digiramp_email = DigirampEmail.create! valid_attributes
        put :update, {:id => digiramp_email.to_param, :digiramp_email => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested digiramp_email" do
      digiramp_email = DigirampEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => digiramp_email.to_param}, valid_session
      }.to change(DigirampEmail, :count).by(-1)
    end

    it "redirects to the digiramp_emails list" do
      digiramp_email = DigirampEmail.create! valid_attributes
      delete :destroy, {:id => digiramp_email.to_param}, valid_session
      expect(response).to redirect_to(digiramp_emails_url)
    end
  end

end
