require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IronsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Iron. As you add validations to Iron, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IronsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all irons as @irons" do
      iron = Iron.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:irons)).to eq([iron])
    end
  end

  describe "GET show" do
    it "assigns the requested iron as @iron" do
      iron = Iron.create! valid_attributes
      get :show, {:id => iron.to_param}, valid_session
      expect(assigns(:iron)).to eq(iron)
    end
  end

  describe "GET new" do
    it "assigns a new iron as @iron" do
      get :new, {}, valid_session
      expect(assigns(:iron)).to be_a_new(Iron)
    end
  end

  describe "GET edit" do
    it "assigns the requested iron as @iron" do
      iron = Iron.create! valid_attributes
      get :edit, {:id => iron.to_param}, valid_session
      expect(assigns(:iron)).to eq(iron)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Iron" do
        expect {
          post :create, {:iron => valid_attributes}, valid_session
        }.to change(Iron, :count).by(1)
      end

      it "assigns a newly created iron as @iron" do
        post :create, {:iron => valid_attributes}, valid_session
        expect(assigns(:iron)).to be_a(Iron)
        expect(assigns(:iron)).to be_persisted
      end

      it "redirects to the created iron" do
        post :create, {:iron => valid_attributes}, valid_session
        expect(response).to redirect_to(Iron.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved iron as @iron" do
        post :create, {:iron => invalid_attributes}, valid_session
        expect(assigns(:iron)).to be_a_new(Iron)
      end

      it "re-renders the 'new' template" do
        post :create, {:iron => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested iron" do
        iron = Iron.create! valid_attributes
        put :update, {:id => iron.to_param, :iron => new_attributes}, valid_session
        iron.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested iron as @iron" do
        iron = Iron.create! valid_attributes
        put :update, {:id => iron.to_param, :iron => valid_attributes}, valid_session
        expect(assigns(:iron)).to eq(iron)
      end

      it "redirects to the iron" do
        iron = Iron.create! valid_attributes
        put :update, {:id => iron.to_param, :iron => valid_attributes}, valid_session
        expect(response).to redirect_to(iron)
      end
    end

    describe "with invalid params" do
      it "assigns the iron as @iron" do
        iron = Iron.create! valid_attributes
        put :update, {:id => iron.to_param, :iron => invalid_attributes}, valid_session
        expect(assigns(:iron)).to eq(iron)
      end

      it "re-renders the 'edit' template" do
        iron = Iron.create! valid_attributes
        put :update, {:id => iron.to_param, :iron => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested iron" do
      iron = Iron.create! valid_attributes
      expect {
        delete :destroy, {:id => iron.to_param}, valid_session
      }.to change(Iron, :count).by(-1)
    end

    it "redirects to the irons list" do
      iron = Iron.create! valid_attributes
      delete :destroy, {:id => iron.to_param}, valid_session
      expect(response).to redirect_to(irons_url)
    end
  end

end
