require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IssueEventsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # IssueEvent. As you add validations to IssueEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IssueEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all issue_events as @issue_events" do
      issue_event = IssueEvent.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:issue_events)).to eq([issue_event])
    end
  end

  describe "GET show" do
    it "assigns the requested issue_event as @issue_event" do
      issue_event = IssueEvent.create! valid_attributes
      get :show, {:id => issue_event.to_param}, valid_session
      expect(assigns(:issue_event)).to eq(issue_event)
    end
  end

  describe "GET new" do
    it "assigns a new issue_event as @issue_event" do
      get :new, {}, valid_session
      expect(assigns(:issue_event)).to be_a_new(IssueEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested issue_event as @issue_event" do
      issue_event = IssueEvent.create! valid_attributes
      get :edit, {:id => issue_event.to_param}, valid_session
      expect(assigns(:issue_event)).to eq(issue_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IssueEvent" do
        expect {
          post :create, {:issue_event => valid_attributes}, valid_session
        }.to change(IssueEvent, :count).by(1)
      end

      it "assigns a newly created issue_event as @issue_event" do
        post :create, {:issue_event => valid_attributes}, valid_session
        expect(assigns(:issue_event)).to be_a(IssueEvent)
        expect(assigns(:issue_event)).to be_persisted
      end

      it "redirects to the created issue_event" do
        post :create, {:issue_event => valid_attributes}, valid_session
        expect(response).to redirect_to(IssueEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved issue_event as @issue_event" do
        post :create, {:issue_event => invalid_attributes}, valid_session
        expect(assigns(:issue_event)).to be_a_new(IssueEvent)
      end

      it "re-renders the 'new' template" do
        post :create, {:issue_event => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested issue_event" do
        issue_event = IssueEvent.create! valid_attributes
        put :update, {:id => issue_event.to_param, :issue_event => new_attributes}, valid_session
        issue_event.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested issue_event as @issue_event" do
        issue_event = IssueEvent.create! valid_attributes
        put :update, {:id => issue_event.to_param, :issue_event => valid_attributes}, valid_session
        expect(assigns(:issue_event)).to eq(issue_event)
      end

      it "redirects to the issue_event" do
        issue_event = IssueEvent.create! valid_attributes
        put :update, {:id => issue_event.to_param, :issue_event => valid_attributes}, valid_session
        expect(response).to redirect_to(issue_event)
      end
    end

    describe "with invalid params" do
      it "assigns the issue_event as @issue_event" do
        issue_event = IssueEvent.create! valid_attributes
        put :update, {:id => issue_event.to_param, :issue_event => invalid_attributes}, valid_session
        expect(assigns(:issue_event)).to eq(issue_event)
      end

      it "re-renders the 'edit' template" do
        issue_event = IssueEvent.create! valid_attributes
        put :update, {:id => issue_event.to_param, :issue_event => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested issue_event" do
      issue_event = IssueEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => issue_event.to_param}, valid_session
      }.to change(IssueEvent, :count).by(-1)
    end

    it "redirects to the issue_events list" do
      issue_event = IssueEvent.create! valid_attributes
      delete :destroy, {:id => issue_event.to_param}, valid_session
      expect(response).to redirect_to(issue_events_url)
    end
  end

end
