require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MandrillTestersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MandrillTester. As you add validations to MandrillTester, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MandrillTestersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all mandrill_testers as @mandrill_testers" do
      mandrill_tester = MandrillTester.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mandrill_testers)).to eq([mandrill_tester])
    end
  end

  describe "GET #show" do
    it "assigns the requested mandrill_tester as @mandrill_tester" do
      mandrill_tester = MandrillTester.create! valid_attributes
      get :show, {:id => mandrill_tester.to_param}, valid_session
      expect(assigns(:mandrill_tester)).to eq(mandrill_tester)
    end
  end

  describe "GET #new" do
    it "assigns a new mandrill_tester as @mandrill_tester" do
      get :new, {}, valid_session
      expect(assigns(:mandrill_tester)).to be_a_new(MandrillTester)
    end
  end

  describe "GET #edit" do
    it "assigns the requested mandrill_tester as @mandrill_tester" do
      mandrill_tester = MandrillTester.create! valid_attributes
      get :edit, {:id => mandrill_tester.to_param}, valid_session
      expect(assigns(:mandrill_tester)).to eq(mandrill_tester)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MandrillTester" do
        expect {
          post :create, {:mandrill_tester => valid_attributes}, valid_session
        }.to change(MandrillTester, :count).by(1)
      end

      it "assigns a newly created mandrill_tester as @mandrill_tester" do
        post :create, {:mandrill_tester => valid_attributes}, valid_session
        expect(assigns(:mandrill_tester)).to be_a(MandrillTester)
        expect(assigns(:mandrill_tester)).to be_persisted
      end

      it "redirects to the created mandrill_tester" do
        post :create, {:mandrill_tester => valid_attributes}, valid_session
        expect(response).to redirect_to(MandrillTester.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved mandrill_tester as @mandrill_tester" do
        post :create, {:mandrill_tester => invalid_attributes}, valid_session
        expect(assigns(:mandrill_tester)).to be_a_new(MandrillTester)
      end

      it "re-renders the 'new' template" do
        post :create, {:mandrill_tester => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mandrill_tester" do
        mandrill_tester = MandrillTester.create! valid_attributes
        put :update, {:id => mandrill_tester.to_param, :mandrill_tester => new_attributes}, valid_session
        mandrill_tester.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mandrill_tester as @mandrill_tester" do
        mandrill_tester = MandrillTester.create! valid_attributes
        put :update, {:id => mandrill_tester.to_param, :mandrill_tester => valid_attributes}, valid_session
        expect(assigns(:mandrill_tester)).to eq(mandrill_tester)
      end

      it "redirects to the mandrill_tester" do
        mandrill_tester = MandrillTester.create! valid_attributes
        put :update, {:id => mandrill_tester.to_param, :mandrill_tester => valid_attributes}, valid_session
        expect(response).to redirect_to(mandrill_tester)
      end
    end

    context "with invalid params" do
      it "assigns the mandrill_tester as @mandrill_tester" do
        mandrill_tester = MandrillTester.create! valid_attributes
        put :update, {:id => mandrill_tester.to_param, :mandrill_tester => invalid_attributes}, valid_session
        expect(assigns(:mandrill_tester)).to eq(mandrill_tester)
      end

      it "re-renders the 'edit' template" do
        mandrill_tester = MandrillTester.create! valid_attributes
        put :update, {:id => mandrill_tester.to_param, :mandrill_tester => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested mandrill_tester" do
      mandrill_tester = MandrillTester.create! valid_attributes
      expect {
        delete :destroy, {:id => mandrill_tester.to_param}, valid_session
      }.to change(MandrillTester, :count).by(-1)
    end

    it "redirects to the mandrill_testers list" do
      mandrill_tester = MandrillTester.create! valid_attributes
      delete :destroy, {:id => mandrill_tester.to_param}, valid_session
      expect(response).to redirect_to(mandrill_testers_url)
    end
  end

end
