require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlaylistEmailsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlaylistEmail. As you add validations to PlaylistEmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlaylistEmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all playlist_emails as @playlist_emails" do
      playlist_email = PlaylistEmail.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:playlist_emails)).to eq([playlist_email])
    end
  end

  describe "GET #show" do
    it "assigns the requested playlist_email as @playlist_email" do
      playlist_email = PlaylistEmail.create! valid_attributes
      get :show, {:id => playlist_email.to_param}, valid_session
      expect(assigns(:playlist_email)).to eq(playlist_email)
    end
  end

  describe "GET #new" do
    it "assigns a new playlist_email as @playlist_email" do
      get :new, {}, valid_session
      expect(assigns(:playlist_email)).to be_a_new(PlaylistEmail)
    end
  end

  describe "GET #edit" do
    it "assigns the requested playlist_email as @playlist_email" do
      playlist_email = PlaylistEmail.create! valid_attributes
      get :edit, {:id => playlist_email.to_param}, valid_session
      expect(assigns(:playlist_email)).to eq(playlist_email)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PlaylistEmail" do
        expect {
          post :create, {:playlist_email => valid_attributes}, valid_session
        }.to change(PlaylistEmail, :count).by(1)
      end

      it "assigns a newly created playlist_email as @playlist_email" do
        post :create, {:playlist_email => valid_attributes}, valid_session
        expect(assigns(:playlist_email)).to be_a(PlaylistEmail)
        expect(assigns(:playlist_email)).to be_persisted
      end

      it "redirects to the created playlist_email" do
        post :create, {:playlist_email => valid_attributes}, valid_session
        expect(response).to redirect_to(PlaylistEmail.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved playlist_email as @playlist_email" do
        post :create, {:playlist_email => invalid_attributes}, valid_session
        expect(assigns(:playlist_email)).to be_a_new(PlaylistEmail)
      end

      it "re-renders the 'new' template" do
        post :create, {:playlist_email => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested playlist_email" do
        playlist_email = PlaylistEmail.create! valid_attributes
        put :update, {:id => playlist_email.to_param, :playlist_email => new_attributes}, valid_session
        playlist_email.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested playlist_email as @playlist_email" do
        playlist_email = PlaylistEmail.create! valid_attributes
        put :update, {:id => playlist_email.to_param, :playlist_email => valid_attributes}, valid_session
        expect(assigns(:playlist_email)).to eq(playlist_email)
      end

      it "redirects to the playlist_email" do
        playlist_email = PlaylistEmail.create! valid_attributes
        put :update, {:id => playlist_email.to_param, :playlist_email => valid_attributes}, valid_session
        expect(response).to redirect_to(playlist_email)
      end
    end

    context "with invalid params" do
      it "assigns the playlist_email as @playlist_email" do
        playlist_email = PlaylistEmail.create! valid_attributes
        put :update, {:id => playlist_email.to_param, :playlist_email => invalid_attributes}, valid_session
        expect(assigns(:playlist_email)).to eq(playlist_email)
      end

      it "re-renders the 'edit' template" do
        playlist_email = PlaylistEmail.create! valid_attributes
        put :update, {:id => playlist_email.to_param, :playlist_email => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested playlist_email" do
      playlist_email = PlaylistEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => playlist_email.to_param}, valid_session
      }.to change(PlaylistEmail, :count).by(-1)
    end

    it "redirects to the playlist_emails list" do
      playlist_email = PlaylistEmail.create! valid_attributes
      delete :destroy, {:id => playlist_email.to_param}, valid_session
      expect(response).to redirect_to(playlist_emails_url)
    end
  end

end
