require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PublishingDealsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PublishingDeal. As you add validations to PublishingDeal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublishingDealsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all publishing_deals as @publishing_deals" do
      publishing_deal = PublishingDeal.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:publishing_deals)).to eq([publishing_deal])
    end
  end

  describe "GET #show" do
    it "assigns the requested publishing_deal as @publishing_deal" do
      publishing_deal = PublishingDeal.create! valid_attributes
      get :show, {:id => publishing_deal.to_param}, valid_session
      expect(assigns(:publishing_deal)).to eq(publishing_deal)
    end
  end

  describe "GET #new" do
    it "assigns a new publishing_deal as @publishing_deal" do
      get :new, {}, valid_session
      expect(assigns(:publishing_deal)).to be_a_new(PublishingDeal)
    end
  end

  describe "GET #edit" do
    it "assigns the requested publishing_deal as @publishing_deal" do
      publishing_deal = PublishingDeal.create! valid_attributes
      get :edit, {:id => publishing_deal.to_param}, valid_session
      expect(assigns(:publishing_deal)).to eq(publishing_deal)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PublishingDeal" do
        expect {
          post :create, {:publishing_deal => valid_attributes}, valid_session
        }.to change(PublishingDeal, :count).by(1)
      end

      it "assigns a newly created publishing_deal as @publishing_deal" do
        post :create, {:publishing_deal => valid_attributes}, valid_session
        expect(assigns(:publishing_deal)).to be_a(PublishingDeal)
        expect(assigns(:publishing_deal)).to be_persisted
      end

      it "redirects to the created publishing_deal" do
        post :create, {:publishing_deal => valid_attributes}, valid_session
        expect(response).to redirect_to(PublishingDeal.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved publishing_deal as @publishing_deal" do
        post :create, {:publishing_deal => invalid_attributes}, valid_session
        expect(assigns(:publishing_deal)).to be_a_new(PublishingDeal)
      end

      it "re-renders the 'new' template" do
        post :create, {:publishing_deal => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested publishing_deal" do
        publishing_deal = PublishingDeal.create! valid_attributes
        put :update, {:id => publishing_deal.to_param, :publishing_deal => new_attributes}, valid_session
        publishing_deal.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested publishing_deal as @publishing_deal" do
        publishing_deal = PublishingDeal.create! valid_attributes
        put :update, {:id => publishing_deal.to_param, :publishing_deal => valid_attributes}, valid_session
        expect(assigns(:publishing_deal)).to eq(publishing_deal)
      end

      it "redirects to the publishing_deal" do
        publishing_deal = PublishingDeal.create! valid_attributes
        put :update, {:id => publishing_deal.to_param, :publishing_deal => valid_attributes}, valid_session
        expect(response).to redirect_to(publishing_deal)
      end
    end

    context "with invalid params" do
      it "assigns the publishing_deal as @publishing_deal" do
        publishing_deal = PublishingDeal.create! valid_attributes
        put :update, {:id => publishing_deal.to_param, :publishing_deal => invalid_attributes}, valid_session
        expect(assigns(:publishing_deal)).to eq(publishing_deal)
      end

      it "re-renders the 'edit' template" do
        publishing_deal = PublishingDeal.create! valid_attributes
        put :update, {:id => publishing_deal.to_param, :publishing_deal => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested publishing_deal" do
      publishing_deal = PublishingDeal.create! valid_attributes
      expect {
        delete :destroy, {:id => publishing_deal.to_param}, valid_session
      }.to change(PublishingDeal, :count).by(-1)
    end

    it "redirects to the publishing_deals list" do
      publishing_deal = PublishingDeal.create! valid_attributes
      delete :destroy, {:id => publishing_deal.to_param}, valid_session
      expect(response).to redirect_to(publishing_deals_url)
    end
  end

end
